import React from "react";
import LegalDocument, { LegalSection, LegalList, LegalLink } from "./legal/LegalDocument";
import {
  LEGAL_CONTACT_EMAIL,
  LEGAL_OPERATOR_NAME,
  LEGAL_SERVICE_NAME,
  LEGAL_WEBSITE_URL,
  legalContactDisplay,
} from "../constants/legal";

const PrivacyPolicy = () => (
  <LegalDocument title="Privacy Policy">
    <p>
      This Privacy Policy describes how {LEGAL_OPERATOR_NAME} (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;)
      collects, uses, and shares information when you use the {LEGAL_SERVICE_NAME} website and related services
      (the &quot;Service&quot;) at{" "}
      <a href={LEGAL_WEBSITE_URL} className="underline">
        {LEGAL_WEBSITE_URL}
      </a>
      .
    </p>
    <p>
      By creating an account or using the Service, you acknowledge this Policy. If you do not agree, do not use the
      Service.
    </p>

    <LegalSection title="1. Who operates the Service">
      <p>
        The Service is operated by {LEGAL_OPERATOR_NAME}. For privacy questions or requests, contact us at{" "}
        {LEGAL_CONTACT_EMAIL ? (
          <a href={`mailto:${LEGAL_CONTACT_EMAIL}`} className="underline">
            {LEGAL_CONTACT_EMAIL}
          </a>
        ) : (
          legalContactDisplay()
        )}
        .
      </p>
    </LegalSection>

    <LegalSection title="2. Information we collect">
      <p>We collect information you and your organization provide, and information generated by use of the Service:</p>
      <LegalList
        items={[
          "Account information: name, email address, password (stored by Firebase Authentication, not in plain text by us), role (administrator or driver), and organization or fleet identifiers.",
          "Profile and fleet records: driver roster details (such as name, phone, email, license number, address, hire date, optional photo), vehicle details, fuel entries, reports, geofence definitions, and fleet settings you enter.",
          "Location and tracking data: when a user enables GPS tracking in the browser, we collect latitude, longitude, timestamps, speed where available, route history points, and a device identifier stored in the browser to associate GPS updates with a vehicle.",
          "Notifications and in-app messages generated by the Service.",
          "Preferences stored in your browser or account, such as dark mode and notification settings.",
          "Technical data: standard web server and Firebase logs may include IP address, browser type, and error information needed to operate and secure the Service.",
        ]}
      />
      <p>
        If you sign in with Google, we receive basic profile information from Google (such as your name and email) as
        permitted by your Google account settings.
      </p>
    </LegalSection>

    <LegalSection title="3. How we use information">
      <LegalList
        items={[
          "Provide fleet management features: vehicle assignment, live and historical maps, fuel tracking, reports, geofence alerts, and administrator dashboards.",
          "Authenticate users and enforce access controls (including driver invite codes and membership approval).",
          "Send account-related emails through Firebase (such as password reset links).",
          "Improve reliability, troubleshoot errors, and protect against abuse.",
          "Comply with legal obligations where applicable.",
        ]}
      />
      <p>
        We do not sell your personal information. We do not use your data for third-party advertising based on what we
        know from operating this Service.
      </p>
    </LegalSection>

    <LegalSection title="4. How information is shared">
      <p>Information may be visible to or processed by:</p>
      <LegalList
        items={[
          "Your fleet administrator: if you are a driver, administrators in your organization can see data linked to your account, including assigned vehicles and location data when tracking is active.",
          "Other authorized users in the same fleet organization, according to role and Firestore security rules.",
          "Service providers that help us run the Service, including Google Firebase (authentication, database, storage, and optional cloud functions), Vercel (hosting), and map tile providers used by the application (such as OpenStreetMap contributors via Leaflet). These providers process data on our behalf to deliver the Service.",
          "Law enforcement or other parties when required by applicable law or a valid legal request.",
        ]}
      />
    </LegalSection>

    <LegalSection title="5. Cookies and local storage">
      <p>
        The Service uses browser local storage and session storage for features such as theme preference, a persistent
        device identifier for GPS registration, and temporary quota-protection flags. Firebase Authentication may use
        cookies or similar technologies to keep you signed in. You can clear site data in your browser, but some features
        may stop working until you sign in again.
      </p>
    </LegalSection>

    <LegalSection title="6. Data retention">
      <p>
        We retain information for as long as your account or fleet records exist, or as needed to provide the Service.
        Route history may be deleted automatically after the retention period configured in fleet settings (default 30
        days) when scheduled cleanup functions are deployed. Administrators may delete records through the application
        where those features are available. Backup copies in Firebase may persist for a limited period according to
        Google&apos;s policies.
      </p>
    </LegalSection>

    <LegalSection title="7. Security">
      <p>
        We use Firebase security rules, authenticated access, and HTTPS hosting. No method of transmission or storage is
        completely secure. You are responsible for keeping your password confidential and for activity under your
        account.
      </p>
    </LegalSection>

    <LegalSection title="8. Your choices">
      <LegalList
        items={[
          "Account settings: update preferences in User Settings where available.",
          "Location: GPS collection requires browser permission and an assigned vehicle; you can deny or revoke location permission in your device or browser.",
          "Access or deletion: administrators can remove driver accounts through fleet tools where deployed. Account holders may request access or deletion by contacting us at the email above. Some fleet records may remain under administrator control.",
          "Marketing: we do not send marketing emails as part of the core Service; password and account emails are transactional.",
        ]}
      />
      <p>
        Depending on where you live, you may have additional rights (such as access, correction, or deletion). We will
        respond to valid requests where applicable law requires us to do so.
      </p>
    </LegalSection>

    <LegalSection title="9. Children">
      <p>
        The Service is not directed to children under 16 and is intended for business fleet use. We do not knowingly
        collect personal information from children under 16. If you believe a child has provided information, contact us
        and we will take appropriate steps to delete it.
      </p>
    </LegalSection>

    <LegalSection title="10. International transfers">
      <p>
        Data is stored and processed using Google Firebase and other providers that may operate in countries other than
        yours. By using the Service, you understand that your information may be transferred to and processed in those
        locations.
      </p>
    </LegalSection>

    <LegalSection title="11. Changes">
      <p>
        We may update this Privacy Policy from time to time. We will post the revised version on this page and update the
        effective date. Continued use after changes means you accept the updated Policy.
      </p>
    </LegalSection>

    <LegalSection title="12. Related documents">
      <p>
        See also our <LegalLink to="/terms">Terms of Service</LegalLink>.
      </p>
    </LegalSection>
  </LegalDocument>
);

export default PrivacyPolicy;
